<?php

namespace lotto\UserBundle\Repository;

/**
 * AccountInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
