<?php

namespace lotto\UserBundle\Repository;

/**
 * LottoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LottoRepository extends \Doctrine\ORM\EntityRepository
{
}
