<?php

namespace lotto\UserBundle\Repository;

/**
 * Play_recordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Play_recordRepository extends \Doctrine\ORM\EntityRepository
{
}
