<?php

namespace lotto\UserBundle\Repository;

/**
 * RegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegisterRepository extends \Doctrine\ORM\EntityRepository
{
}
